# Website settings
url: "https://randxie.github.io/"
baseurl: ""

# Internal nav
nav:
  main:
    writing/写作: "/writing"
    speaking: "/speaking"
    projects: "/projects"
  writing:
    all: "/writing"
    english: "/writing/english"
    中文: "/writing/chinese"
    tags: "/writing/tags"

# Bio settings
name: "Rand Xie"
description: "The home page of Rand Xie."
thumbnail_path: "profile-photos/randxie_profile.jpg"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/Randxie29"
    label: "Twitter"
    icon: "twitter-square"
    username: "@Randxie29"
  linkedin:
    url: "https://www.linkedin.com/in/yuyang-rand-xie-48489639/"
    label: "LinkedIn"
    icon: "linkedin-square"
  kaggle:
    url: "https://www.kaggle.com/randxie"
    label: "Kaggle"
    icon: "coffee"
  zhihu:
    url: "https://www.zhihu.com/people/randxie/answers"
    label: "Zhihu"
    icon: "book"
  github:
    url: "https://github.com/randxie"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "randxiexyy29@gmail.com"
    label: "Email"
    value: "randxiexyy29@gmail.com"
    icon: "envelope-square"

uptake_url: "https://www.uptake.com/"
mathworks_url: "https://www.mathworks.com/"
pm_toolbox_url: "https://www.mathworks.com/products/predictive-maintenance.html/"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
markdown: kramdown
kramdown:
    math_engine: katex

disqus:
  shortname: randxie

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate